server:
  port: 8090

spring:
  application:
    name: msvc-user
  datasource:
    url: jdbc:postgresql://localhost:5432/house_now_bd
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    #database: postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
